#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
elif [ "$branch" = "develop" ]; then
  echo "You can't commit directly to master develop"
  exit 1
fi
