version: "3"

services:
  db_postgres:
    networks:
      - carsapi
    restart: on-failure
    image: postgres:12.1-alpine
    container_name: "postgres_carsapi"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD:docker
      - POSTGRES_DB=carsapi
    volumes:
      - "./src/database/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  api_node:
    build: .
    networks:
      - carsapi
    links:
      - db_postgres
    depends_on:
      - db_postgres
    container_name: "node_carsapi"
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
    command: "sh /usr/app/start.sh"
    env_file: .dockerenv

networks:
  carsapi:
